### ISSUE TITLE
3.1 Add ability to display Kudos on Proofs

### ISSUE THREAD

**Issue by SEM24** [Vladyslav-Team/backend#104]
**TODO**
The number of the Kudos is displayed on proof.
Talent can’t add Kudos to their own Proofs.
Kudos is general info, hence Kudos quantity is visible to everyone.

**Comment by PanfiDen** [comment]
Example:

GET: http://localhost:28852/proofs/6/kudos

Body:
{
"proof_id": 6,
"amount_of_kudos": 2
}
