### ISSUE TITLE
4.2.1 ft Display all skills in profile with gray color if they are not verified

### ISSUE THREAD

**Issue by IlliaKyselov1902** [Vladyslav-Team/backend#159]
Colorize skills from gray to skill color on profile page only if at least one proof with certain skill is !published!

**Comment by PanfiDen** [comment]
+ fix [There is some Skills that can`t be added to the Proof. #30](https://github.com/Vladyslav-Team/quality-assurance-engineer/issues/30)

**Comment by SEM24** [comment]
Get: http://localhost:28852/talents/3
Body of response:

{
    "id": 3,
    "image": "https://drive.google.com/uc?export=view&id=1gRLtkAmjB7V5VzXrTYjDHAEyWAEnkc5M",
    "name": "Vladyslav ",
    "surname": "Khrychov",
    "experience": "JavaScript - infinity years",
    "location": "Ukraine",
    "about": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce elit arcu, aliquam in massa vitae, blandit hendrerit nibh. Duis auctor, mi nec fringilla commodo, elit a",
    "education": "KNURE",
    "age": 30,
    "email": "Vladyslav@gmail.com",
    "phone": "380999479826",
    "skills": [
        {
            "skill": {
                "id": 67,
                "title": "Attention to detail"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 50,
                "title": "Postman"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 35,
                "title": "Figma"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 55,
                "title": "Design"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 23,
                "title": "OracleDB"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 32,
                "title": "Windows"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 66,
                "title": "Work ethic"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 22,
                "title": "MSSQL"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 18,
                "title": "TypeScript"
            },
            "verified": true
        },
        {
            "skill": {
                "id": 14,
                "title": "JavaScript"
            },
            "verified": true
        },
        {
            "skill": {
                "id": 13,
                "title": "CSS"
            },
            "verified": true
        },
        {
            "skill": {
                "id": 61,
                "title": "Self-organization"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 59,
                "title": "Fast-learner"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 58,
                "title": "Creativity"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 20,
                "title": "PostgreSQL"
            },
            "verified": true
        },
        {
            "skill": {
                "id": 56,
                "title": "Team-leader"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 24,
                "title": "MongoDB"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 49,
                "title": "Jira"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 64,
                "title": "Adaptability"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 36,
                "title": "Photoshop"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 62,
                "title": "Time management"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 15,
                "title": "XML"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 63,
                "title": "Communication"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 57,
                "title": "Teamwork"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 27,
                "title": "Git"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 21,
                "title": "MySQL"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 12,
                "title": "HTML"
            },
            "verified": true
        },
        {
            "skill": {
                "id": 60,
                "title": "Critical-thinking"
            },
            "verified": false
        },
        {
            "skill": {
                "id": 65,
                "title": "Interpersonal Skills"
            },
            "verified": false
        }
    ],
    "balance": 10
}
