### ISSUE TITLE
5.2. Add ability to view OWN the most Kudosed Proof

### ISSUE THREAD

**Issue by PanfiDen** [Vladyslav-Team/backend#186]
Sort Proof by Kudos (rating)

**Comment by PanfiDen** [comment]
Update(19.05.22):
No sort, just return the most kudosed Proof

**Comment by SEM24** [comment]
Get: http://localhost:28852/talents/3/stats/proofs

Body of response:
{
    "mostKudosed": [
        5
    ]
}
