### ISSUE TITLE
Add endpoint for registration and login

### ISSUE THREAD

**Issue by IlliaKyselov1902** [Vladyslav-Team/backend#38]
Create 2 endpoints to add the ability to perform registration of your account and login into your account using JWT token

**POST /talents**
**POST /talents/login**

**Comment by SEM24** [comment]
_Registration endpoints:_

**Post:** http://localhost:28852/talents

**Body:**
{
    "name": "Ivan2",
    "surname": "Fedotov",
    "email": "test@gmail.com",
    "password": "123456",
    "location":"Ukraine",
    "dateOfBirth": "2000-12-12"
}

**Response:** 
{
    "jwt-token": "eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJTa2lsbFNjb3BlIiwic3ViIjoidGVzdEBnbWFpbC5jb20iLCJpZCI6MjgsImV4cCI6MTY4MDIxNTgyNiwiaWF0IjoxNjgwMjEzMTI2fQ.giNJhvji5gxpbOr_YAtQzQYOpJ15LGU-Zc-DzghZuRyNi3xznKsCMoxE3jfkiy7BXkmjIxr0rqqWXnnoVghkg9LrAlkcaBjfvwMTsHz163ljMbASk6nPlPU2vwR2wrzgWJyYDM8Th-IW0UH3QNnAFwkVks70vmOn8wbgQILpviN6RKIZsw8PUV3L90T9NzkMKiy1CdXD6R5lrMykq7w50ndOAWYsnLHVZARwUouD4VWhzG6uajzo3OqOc7M589rQgNTrmsIffN1GH8MZ-vXA5ptsSLq3ezrg3SHUO2ItGku7Tb1VRWaWpA4kRmDwlRdQPc6fr4xoOtKypK-Q_0u5hA"
}

_Login endpoins:_

**Post:**  http://localhost:28852/talents/login

**Respose:**
{
    "jwt-token": "eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJTa2lsbFNjb3BlIiwic3ViIjoidGVzdEBnbWFpbC5jb20iLCJpZCI6MjgsImV4cCI6MTY4MDIxNTgzMSwiaWF0IjoxNjgwMjEzMTMxfQ.UbUO6c0vfYcub1d1t_WgxCP4zm3_c_047GYoh05rEG3xlz_tMMwY1AkqsS-lfrfdj1cR9Du3arRHxc7RQfLzvucz0pcFopsLh50J1KPOrSx91VAYRRdobfHM-kHpzBWKe6P3zTHZ2WHYEcjtWgMWtLy1askzElnJFvkN0JMOktA7muHDOW6FQp7vVq1ucm6SlATF_SY_qx3oWVak0abYY4wLTWYFBL-x_oNOw0ysXEMI3l0ZA_rQoMysgl_lhtoOtagT69nZr0d8K1a9c56xT3FbUn0iauTqUcYS5CJ4pNVl2JwFPrwPumxxW-_LhrJrsPqwLaHLV4A1I26HfzMDVA"
}

**Comment by PanfiDen** [comment]
Registration 
new Body example:
{
    "name": "Test",
    "surname": "Qwe",
    "email": "testfsdfsf@gmail.com",
    "password": "secret",
    "location": "Ukraine",
    "birthday":"09-09-1999"
}
