### ISSUE TITLE
1.3 Add the ability to edit fields and save or delete changes only your account

### ISSUE THREAD

**Issue by IlliaKyselov1902** [Vladyslav-Team/backend#8]
User must be authorized to change it's account

**Comment by IlliaKyselov1902** [comment]
Blocker: you need to implement registration/login first

**Comment by SEM24** [comment]
**_Approximate body example_**
**Patch** http://localhost:28852/talents/28

{
    "password": "midostar100035",
    "name": "Ivan22",
    "surname": "Fedotov2",
    "image":"https://www.headphonesty.com/wp-content/uploads/2022/01/Logitech_G_Pro_X_design.jpg",
    "location":"Ukraine",
    "about": "test test",
    "education":"",
    "birthday": "02-01-1999",
    "phone":"+380938767114"
}
